=== DanieleCalisiIT/E-commerce_website/LinguaggiPerIlWeb_Progetto/XML/categorie.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
                        
<xsd:element name="categorie">
  <xsd:complexType>
    <xsd:sequence>
      <xsd:element ref="categoria" maxOccurs="unbounded"/>
    </xsd:sequence>  
  </xsd:complexType>
</xsd:element>

<xsd:element name ="categoria">
    <xsd:complexType>
    <xsd:sequence>
        <xsd:element ref="idCateg"/>
        <xsd:element ref="nome"/>
        <xsd:element ref="descrizione"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="idCateg" type="xsd:integer"/>
<xsd:element name="nome" type="xsd:string"/>
<xsd:element name="descrizione" type="xsd:string"/>
        

</xsd:schema>

=== DanieleCalisiIT/E-commerce_website/LinguaggiPerIlWeb_Progetto/XML/categorie.xml
<?xml version="1.0" encoding="UTF-8"?>
<categorie xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="categorie.xsd">
<categoria>
    <idCateg>1</idCateg>
    <nome>Famiglia</nome>
    <descrizione>Gioco ideale per una serata in famiglia</descrizione>
</categoria>
<categoria>
    <idCateg>2</idCateg>
    <nome>Strategia</nome>
    <descrizione>Gioco di strategia 8==D</descrizione>
</categoria>
<categoria>
    <idCateg>3</idCateg>
    <nome>Party</nome>
    <descrizione>Party game O.O</descrizione>
</categoria>
</categorie>
