=== DanieleCalisiIT/E-commerce_website/LinguaggiPerIlWeb_Progetto/XML/domande.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
                        
<xsd:element name="discussioni">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="domanda" maxOccurs="unbounded"/>
</xsd:sequence>
</xsd:complexType>
</xsd:element>

<xsd:element name="domanda">
  <xsd:complexType>
    <xsd:sequence>
      <xsd:element ref="idDom"/>
      <xsd:element ref="dataCreaz" />
      <xsd:element ref="creatore" />
      <xsd:element ref="testo" />
      <xsd:element ref="risposta" minOccurs="0" maxOccurs="unbounded"/>
      <xsd:element ref="votoDomanda" minOccurs="0" maxOccurs="unbounded"/>    
    </xsd:sequence>  
    <xsd:attribute name="stato" type="xsd:string" use="required" />
  </xsd:complexType>
</xsd:element>

<xsd:element name="idDom" type="xsd:integer" />
<xsd:element name="dataCreaz" type="xsd:date" />
<xsd:element name="creatore" type="xsd:string" />
<xsd:element name="testo" type="xsd:string" />
<xsd:element name="risposta" type="risposta" />
<xsd:element name="votoDomanda" type="voto" />

<xsd:complexType name="risposta">
      <xsd:sequence>
         <xsd:element ref="idRisp" />
         <xsd:element ref="dataCreaz" />
         <xsd:element ref="creatore" />
         <xsd:element ref="testo" />
         <xsd:element ref="votoRisposta" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
</xsd:complexType>

<xsd:element name="idRisp" type="xsd:integer"/>
<xsd:element name="utente" type="xsd:string"/>
<xsd:element name="testo" type="xsd:string"/>
<xsd:element name="votoRisposta" type="voto" />


<xsd:complexType name="voto">
      <xsd:sequence>
         <xsd:element ref="creatore" />
         <xsd:element ref="valoreVoto" />
      </xsd:sequence>
</xsd:complexType>

<xsd:element name="valoreVoto" type="xsd:string"/>

</xsd:schema>

=== DanieleCalisiIT/E-commerce_website/LinguaggiPerIlWeb_Progetto/XML/domande.xml
<?xml version="1.0" encoding="UTF-8"?>
<discussioni xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="domande.xsd"><domanda stato="aperta"><idDom>4</idDom><dataCreaz>2019-07-01</dataCreaz><creatore>cliente1</creatore><testo>ciaociao</testo></domanda><domanda stato="chiusa"><idDom>1</idDom><dataCreaz>2019-07-01</dataCreaz><creatore>cliente1</creatore><testo>fffffffffffffffff</testo></domanda><domanda stato="aperta"><idDom>2</idDom><dataCreaz>2019-07-01</dataCreaz><creatore>cliente1</creatore><testo>asdasdasdas</testo><risposta><idRisp>4</idRisp><dataCreaz>2019-07-01</dataCreaz><creatore>gestore1</creatore><testo>ciao</testo></risposta><votoDomanda><creatore>cliente3</creatore><valoreVoto>true</valoreVoto></votoDomanda></domanda><domanda stato="aperta"><idDom>3</idDom><dataCreaz>1999-02-01</dataCreaz><creatore>cliente2</creatore><testo>Quanto fa pena Gianluca?</testo><risposta><idRisp>1</idRisp><dataCreaz>2019-06-29</dataCreaz><creatore>cliente1</creatore><testo>prova</testo></risposta><risposta><idRisp>2</idRisp><dataCreaz>2019-06-29</dataCreaz><creatore>cliente1</creatore><testo>prova1</testo></risposta><risposta><idRisp>3</idRisp><dataCreaz>2019-06-30</dataCreaz><creatore>cliente1</creatore><testo>prova prova</testo></risposta><votoDomanda><creatore>cliente1</creatore><valoreVoto>true</valoreVoto></votoDomanda></domanda></discussioni>
