=== DanieleCalisiIT/E-commerce_website/LinguaggiPerIlWeb_Progetto/XML/faq.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<xsd:element name="faq">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="domanda" maxOccurs="unbounded"/>
</xsd:sequence>
</xsd:complexType>
</xsd:element>

<xsd:element name="domanda">
  <xsd:complexType>
    <xsd:sequence>
      <xsd:element ref="idFaq"/>
      <xsd:element ref="domandaFAQ"/>
      <xsd:element ref="risposta"/>
    </xsd:sequence>
  </xsd:complexType>
</xsd:element>

<xsd:element name="idFaq" type="xsd:integer"/>
<xsd:element name="domandaFAQ" type="xsd:string"/>
<xsd:element name="risposta" type="xsd:string"/>

</xsd:schema>

=== DanieleCalisiIT/E-commerce_website/LinguaggiPerIlWeb_Progetto/XML/faq.xml
<?xml version="1.0" encoding="UTF-8"?>
<faq xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="faq.xsd"><domanda><idFaq>1</idFaq><domandaFAQ>Con che corriere spedite la merce?</domandaFAQ><risposta>Con Bartolini o GLS</risposta></domanda><domanda><idFaq>2</idFaq><domandaFAQ>Quali sono i tempi di spedizione?</domandaFAQ><risposta>I tempi di spedizione variano in base al corriere utilizzato e al paese di destinazione. Generalmente variano tra 3 e 10 giorni</risposta></domanda><domanda><idFaq>3</idFaq><domandaFAQ>Quanto fa pena Gianluca?</domandaFAQ><risposta>Parecchio</risposta></domanda><domanda><idFaq>4</idFaq><domandaFAQ>ciaociao</domandaFAQ><risposta>ciao</risposta></domanda></faq>
