=== DanieleCalisiIT/E-commerce_website/LinguaggiPerIlWeb_Progetto/XML/indirizzi.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
                        
  <xsd:element name="lista_indirizzi">
  <xsd:complexType>
    <xsd:sequence>
      <xsd:element ref="indirizzo" maxOccurs="unbounded"/>
    </xsd:sequence>  
  </xsd:complexType>
</xsd:element>

<xsd:element name ="indirizzo">
    <xsd:complexType>
    <xsd:sequence>
        <xsd:element ref="id"/>
        <xsd:element ref="citta"/>
        <xsd:element ref="cap"/>
        <xsd:element ref="provincia"/>
        <xsd:element ref="regione"/>
        <xsd:element ref="nazione"/>
        <xsd:element ref="via"/>
        <xsd:element ref="civico"/>    
    </xsd:sequence>
    </xsd:complexType>
</xsd:element>

<xsd:element name="id" type="xsd:integer"/>
<xsd:element name="citta" type="xsd:string"/>
<xsd:element name="cap" type="xsd:integer"/>
<xsd:element name="provincia" type="xsd:string"/>
<xsd:element name="regione" type="xsd:string"/>
<xsd:element name="nazione" type="xsd:string"/>
<xsd:element name="via" type="xsd:string"/>
<xsd:element name="civico" type="xsd:integer"/>
</xsd:schema>

=== DanieleCalisiIT/E-commerce_website/LinguaggiPerIlWeb_Progetto/XML/indirizzi.xml
<?xml version="1.0" encoding="UTF-8"?>
<lista_indirizzi xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="indirizzi.xsd"><indirizzo><id>1</id><citta>Milano</citta><cap>20019</cap><provincia>Milano</provincia><regione>Lombardia</regione><nazione>Italia</nazione><via>Garibaldi</via><civico>2</civico></indirizzo><indirizzo><id>2</id><citta>Roma</citta><cap>64</cap><provincia>Roma</provincia><regione>Lazio</regione><nazione>Italia</nazione><via>del Corso</via><civico>5</civico></indirizzo><indirizzo><id>3</id><citta>Roma</citta><cap>00020</cap><provincia>Roma</provincia><regione>Lazio</regione><nazione>Italia</nazione><via>Corso</via><civico>3</civico></indirizzo></lista_indirizzi>
