=== DanieleCalisiIT/E-commerce_website/LinguaggiPerIlWeb_Progetto/XML/prodotti.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

<xsd:element name="prodotti">
  <xsd:complexType>
    <xsd:sequence>
      <xsd:element ref="gioco" maxOccurs="unbounded"/>
    </xsd:sequence>  
  </xsd:complexType>
</xsd:element>

<xsd:element name ="gioco">
    <xsd:complexType>
    <xsd:sequence>
        <xsd:element ref="idProd"/>  
        <xsd:element ref="nome"/>
        <xsd:element ref="idCateg"/>
        <xsd:element ref="idCasa"/>
        <xsd:element ref="lingua"/>
        <xsd:element ref="annoProd"/>
        <xsd:element ref="prezzo"/>
        <xsd:element ref="img"/>
        <xsd:element ref="idSconto" minOccurs="0" maxOccurs="unbounded"/>    
    </xsd:sequence>
    </xsd:complexType>
</xsd:element>

<xsd:element name="idProd" type="xsd:integer"/>
<xsd:element name="nome" type="xsd:string"/>
<xsd:element name="idCateg" type="xsd:string"/>
<xsd:element name="idCasa" type="xsd:string"/>
<xsd:element name="lingua" type="xsd:string"/>
<xsd:element name="annoProd" type="xsd:string"/>
<xsd:element name="prezzo" type="xsd:double"/>
<xsd:element name="img" type="xsd:string"/>
<xsd:element name="idSconto" type="xsd:integer"/>
</xsd:schema>

=== DanieleCalisiIT/E-commerce_website/LinguaggiPerIlWeb_Progetto/XML/prodotti.xml
<?xml version="1.0" encoding="UTF-8"?>
<prodotti xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="prodotti.xsd"><gioco><idProd>1</idProd><nome>Monopoli</nome><idCateg>1</idCateg><idCasa>1</idCasa><lingua>Italiano</lingua><annoProd>2001</annoProd><prezzo>20</prezzo><img>../images/Monopoli1.png</img><idSconto>1</idSconto></gioco><gioco><idProd>2</idProd><nome>Risiko</nome><idCateg>2</idCateg><idCasa>2</idCasa><lingua>Inglese</lingua><annoProd>1995</annoProd><prezzo>45</prezzo><img>../images/Risiko2.png</img><idSconto>1</idSconto><idSconto>2</idSconto></gioco><gioco><idProd>3</idProd><nome>prova</nome><idCateg>1</idCateg><idCasa>1</idCasa><lingua>Inglese</lingua><annoProd>2000</annoProd><prezzo>2</prezzo><img>../images/prova3.png</img></gioco></prodotti>
