=== DanieleCalisiIT/E-commerce_website/LinguaggiPerIlWeb_Progetto/XML/richieste.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<xsd:element name="richieste">
  <xsd:complexType>
    <xsd:sequence>
      <xsd:element ref="richiesta" maxOccurs="unbounded"/>
    </xsd:sequence>  
  </xsd:complexType>
</xsd:element>

<xsd:element name ="richiesta">
    <xsd:complexType>
    <xsd:sequence>
        <xsd:element ref="idRich"/>
        <xsd:element ref="importo"/>
        <xsd:element ref="idAcc"/>
    </xsd:sequence>
    </xsd:complexType>
</xsd:element>

<xsd:element name="idRich" type="xsd:integer"/>
<xsd:element name="importo" type="xsd:double"/>
<xsd:element name="idAcc" type="xsd:integer"/>

</xsd:schema>

=== DanieleCalisiIT/E-commerce_website/LinguaggiPerIlWeb_Progetto/XML/richieste.xml
<?xml version="1.0" encoding="UTF-8"?>
<richieste xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="richieste.xsd"><richiesta><idRich>1</idRich><importo>3.05</importo><idAcc>5</idAcc></richiesta><richiesta><idRich>2</idRich><importo>20</importo><idAcc>5</idAcc></richiesta></richieste>
