=== DanieleCalisiIT/E-commerce_website/LinguaggiPerIlWeb_Progetto/XML/sconti.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
                        
 <xsd:element name="sconti">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="sconto" maxOccurs="unbounded"/>
</xsd:sequence>
</xsd:complexType> 
 </xsd:element> 

<xsd:element name="sconto">
  <xsd:complexType>
    <xsd:sequence>
      <xsd:element ref="idSconto"/>
      <xsd:element ref="percentuale"/>
      <xsd:element ref="repNecess"/>
      <xsd:element ref="credNecess"/>
      <xsd:element ref="scadenza"/>
    </xsd:sequence>
    <xsd:attribute name="stato" type="xsd:string" use="required"/>
  </xsd:complexType>
</xsd:element>

<xsd:element name="idSconto" type="xsd:integer"/>
<xsd:element name="percentuale" type="xsd:integer"/>
<xsd:element name="repNecess" type="xsd:integer"/>
<xsd:element name="credNecess" type="xsd:integer"/>
<xsd:element name="scadenza" type="xsd:date"/>
</xsd:schema>

=== DanieleCalisiIT/E-commerce_website/LinguaggiPerIlWeb_Progetto/XML/sconti.xml
<?xml version="1.0" encoding="UTF-8"?>
<sconti xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="sconti.xsd"><sconto stato="attivo"><idSconto>1</idSconto><percentuale>30</percentuale><repNecess>40</repNecess><credNecess>55</credNecess><scadenza>2019-08-21</scadenza></sconto><sconto stato="attivo"><idSconto>2</idSconto><percentuale>60</percentuale><repNecess>80</repNecess><credNecess>99</credNecess><scadenza>2019-08-20</scadenza></sconto><sconto stato="attivo"><idSconto>3</idSconto><percentuale>20</percentuale><repNecess>1</repNecess><credNecess>1</credNecess><scadenza>2019-07-25</scadenza></sconto></sconti>
